# This is a basic workflow to help you get started with Actions

name: 🔨 Auto Generating Tasks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - "**.md"
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: commit-work
  cancel-in-progress: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  linking:
    runs-on: ubuntu-latest
    name: Linking markdown files
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: ⌛ Get Time
        id: time
        uses: nanzm/get-time-action@v2.0
        with:
          timeZone: 8
          format: "YYYY-MM-DD"

      - name: 📑 Link Markdown files
        uses: DaanV2/Markdown-Linker@latest
        with:
          ignore: |
            README.md

      - name: 📖 Commit changes
        continue-on-error: true
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.email "github-action@github.com"
          git config --global user.name "Tasha"
          git add .
          git commit -m "auto: 📑 Applied linking ${{ steps.time.outputs.time }}"

      # Runs a single command using the runners shell
      - name: 📓 Create Readmes
        uses: DaanV2/Markdown-Action-Create-Indexes@v3.0.0
        with:
          folder: ${{github.workspace}}
          filename: README.md

      - name: 📖 Commit changes
        continue-on-error: true
        run: |
          cd $GITHUB_WORKSPACE
          git add .
          git commit -m "auto: 📓 Generated Readme ${{ steps.time.outputs.time }}"

      - name: 🚚 Push
        continue-on-error: true
        run: git push
